name: HACS Validation

on:
  push:
    branches:
      - 4.0-dev
  pull_request:
    branches:
      - 4.0-dev

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run HACS Action
        uses: hacs/action@main
        with:
          category: integration
